# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

xl_check_grammar_ <- function() {
    invisible(.Call('xltoken_xl_check_grammar_', PACKAGE = 'xltoken'))
}

xl_formula_ <- function(x) {
    .Call('xltoken_xl_formula_', PACKAGE = 'xltoken', x)
}

